/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/my-futuristic-concept-car/source/base_basic_pbr.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/base_basic_pbr.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials.CustomMaterial} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/base_basic_pbr.glb')
